github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/hentaihaven-downloader",
  "https://serp.co/products/hentaihaven-downloader/reviews/",
  "https://extensions.serp.co/hentaihaven-downloader",
  "https://browserextensions.io/hentaihaven-downloader"
]
